In [1]:
# ============================================================
# Session 10 - ABC3 Perovskite Data Profiling & Imputation
# ============================================================

import pandas as pd
from ydata_profiling import ProfileReport
from sklearn.impute import SimpleImputer, KNNImputer


# ------------------------------------------------------------
# 1. Load dataset from Session 09
# ------------------------------------------------------------

df = pd.read_csv("perovskites_data.csv")

print("✅ Dataset loaded successfully")
print(f"Rows: {df.shape[0]}")
print(f"Columns: {df.shape[1]}")

display(df.head(10))


# ------------------------------------------------------------
# 2. Check columns
# ------------------------------------------------------------

print("\n📌 Dataset columns:")
print(df.columns.tolist())


# ------------------------------------------------------------
# 3. Check missing values
# ------------------------------------------------------------

print("\n📌 Missing values BEFORE imputation:")
print(df.isnull().sum())


# ------------------------------------------------------------
# 4. Generate profiling report
# ------------------------------------------------------------

profile = ProfileReport(
    df,
    title="ABC3 Perovskites Data Profiling Report",
    explorative=True
)

profile.to_file(
    "perovskites_data_report.html"
)

print("\n✅ Profiling report generated!")
print("📄 perovskites_data_report.html")


# ------------------------------------------------------------
# 5. Mean Imputation
# ------------------------------------------------------------

mean_imputer = SimpleImputer(
    strategy="mean"
)

df_mean_imputed = df.copy()

df_mean_imputed[["Bandgap"]] = (
    mean_imputer.fit_transform(
        df[["Bandgap"]]
    )
)

print("\n✅ Mean imputation completed")


# ------------------------------------------------------------
# 6. KNN Imputation
# ------------------------------------------------------------

numeric_columns = [
    "Bandgap",
    "Formation_Energy_per_Atom",
    "Volume"
]

df_knn_imputed = df.copy()

knn_imputer = KNNImputer(
    n_neighbors=5
)

df_knn_imputed[numeric_columns] = (
    knn_imputer.fit_transform(
        df[numeric_columns]
    )
)

print("✅ KNN imputation completed")


# ------------------------------------------------------------
# 7. Check missing values AFTER imputation
# ------------------------------------------------------------

print("\n📌 Missing values AFTER Mean Imputation:")
print(df_mean_imputed.isnull().sum())

print("\n📌 Missing values AFTER KNN Imputation:")
print(df_knn_imputed.isnull().sum())


# ------------------------------------------------------------
# 8. Save mean-imputed dataset
# ------------------------------------------------------------

df_mean_imputed.to_csv(
    "perovskites_mean_imputed.csv",
    index=False
)

print("\n✅ Mean-imputed dataset saved:")
print("   perovskites_mean_imputed.csv")


# ------------------------------------------------------------
# 9. Save KNN-imputed dataset
# ------------------------------------------------------------

df_knn_imputed.to_csv(
    "perovskites_knn_imputed.csv",
    index=False
)

print("\n✅ KNN-imputed dataset saved:")
print("   perovskites_knn_imputed.csv")


# ------------------------------------------------------------
# 10. Final dataset preview
# ------------------------------------------------------------

print("\n📊 Final KNN-imputed dataset:")

display(
    df_knn_imputed.head(10)
)

C:\Users\adity\AppData\Local\Temp\ipykernel_35548\3104578138.py:6: DeprecationWarning:
    `import ydata_profiling` is deprecated and will not receive more updates.
    Please install fg-data-profiling via `pip install fg-data-profiling` and use `import data_profiling` instead.

  from ydata_profiling import ProfileReport

✅ Dataset loaded successfully
Rows: 4719
Columns: 5

  Material_ID Formula  Bandgap  Formation_Energy_per_Atom     Volume
0  mp-1183115  AcAlO3   4.1024                  -3.690019  57.451413
1  mp-1183052   AcBO3   0.8071                  -2.475390  51.548126
2   mp-866101  AcCrO3   2.0031                  -3.138972  61.362845
3   mp-864606  AcCuO3   0.0000                  -2.422892  59.929387
4   mp-861502  AcFeO3   1.0084                  -2.771539  61.797311
5  mp-1183053  AcGaO3   2.8959                  -3.063253  61.455078
6  mp-1183142  AcMgO3   0.0000                  -3.001845  64.783754
7   mp-864911  AcMnO3   0.0000                  -2.973630  62.241399
8  mp-1183139  AcNiO3   0.0000                  -2.455477  58.358218
9  mp-1183145  AcPdO3   0.0000                  -2.236955  66.686674

📌 Dataset columns:
['Material_ID', 'Formula', 'Bandgap', 'Formation_Energy_per_Atom', 'Volume']

📌 Missing values BEFORE imputation:
Material_ID                  0
Formula                      0
Bandgap                      0
Formation_Energy_per_Atom    0
Volume                       0
dtype: int64

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]
100%|██████████| 5/5 [00:00<00:00, 22.78it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

✅ Profiling report generated!
📄 perovskites_data_report.html

✅ Mean imputation completed
✅ KNN imputation completed

📌 Missing values AFTER Mean Imputation:
Material_ID                  0
Formula                      0
Bandgap                      0
Formation_Energy_per_Atom    0
Volume                       0
dtype: int64

📌 Missing values AFTER KNN Imputation:
Material_ID                  0
Formula                      0
Bandgap                      0
Formation_Energy_per_Atom    0
Volume                       0
dtype: int64

✅ Mean-imputed dataset saved:
   perovskites_mean_imputed.csv

✅ KNN-imputed dataset saved:
   perovskites_knn_imputed.csv

📊 Final KNN-imputed dataset:

  Material_ID Formula  Bandgap  Formation_Energy_per_Atom     Volume
0  mp-1183115  AcAlO3   4.1024                  -3.690019  57.451413
1  mp-1183052   AcBO3   0.8071                  -2.475390  51.548126
2   mp-866101  AcCrO3   2.0031                  -3.138972  61.362845
3   mp-864606  AcCuO3   0.0000                  -2.422892  59.929387
4   mp-861502  AcFeO3   1.0084                  -2.771539  61.797311
5  mp-1183053  AcGaO3   2.8959                  -3.063253  61.455078
6  mp-1183142  AcMgO3   0.0000                  -3.001845  64.783754
7   mp-864911  AcMnO3   0.0000                  -2.973630  62.241399
8  mp-1183139  AcNiO3   0.0000                  -2.455477  58.358218
9  mp-1183145  AcPdO3   0.0000                  -2.236955  66.686674